SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II
JOIN ITEM_TREE IT ON II.ITEM_ID = IT.ITEM_ID
JOIN ITEM_INFO II2 ON IT.PARENT_ITEM_ID = II2.ITEM_ID
WHERE II2.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;