SELECT BK.BOOK_ID, AUT.AUTHOR_NAME, DATE_FORMAT(BK.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK BK 
JOIN AUTHOR AUT ON AUT.AUTHOR_ID = BK.AUTHOR_ID
AND BK.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE;